Sections = {
    "admin" : "Administration Utilities",
    "comm" : "Communication Programs",
    "database" : "Databases",
    "debug" : "Debug packages",
    "devel" : "Development",
    "doc" : "Documentation",
    "editors" : "Editors",
    "electronics" : "Electronics",
    "embedded" : "Embedded software",
    "fonts" : "Fonts",
    "games" : "Games",
    "gnome" : "GNOME",
    "gnustep" : "GNUstep",
    "graphics" : "Graphics",
    "hamradio" : "Ham Radio",
    "haskell" : "Haskell",
    "httpd" : "Web Servers",
    "interpreters" : "Interpreters",
    "java" : "Java",
    "kde" : "KDE",
    "kernel" : "Kernels",
    "libdevel" : "Library development",
    "libs" : "Libraries",
    "lisp" : "Lisp",
    "localization" : "Language packs",
    "mail" : "Mail",
    "math" : "Mathematics",
    "misc" : "Miscellaneous",
    "net" : "Network",
    "news" : "Newsgroups",
    "ocaml" : "OCaml",
    "oldlibs" : "Old Libraries",
    "otherosfs" : "Other OS's and file systems",
    "perl" : "Perl",
    "php" : "PHP",
    "python" : "Python",
    "ruby" : "Ruby",
    "science" : "Science",
    "shells" : "Shells",
    "sound" : "Sound",
    "tex" : "TeX",
    "text" : "Text Processing",
    "translations" : "Translations",
    "utils" : "Utilities",
    "vcs" : "Version Control Systems",
    "video" : "Video",
    "virtual" : "Virtual packages",
    "web" : "Web Software",
    "x11" : "X Window System software",
    "xfce" : "Xfce",
    "zope" : "Zope/Plone Framework",
}
